import { createClient } from "npm:@supabase/supabase-js@2";
import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "npm:pdf-lib@1.17.1";
import {
  corsHeaders,
  extractBearerToken,
  jsonResponse,
  serializeError,
} from "../_shared/http.ts";

const RECEIPT_BUCKET = "order-receipts";

function getEnv(name: string) {
  const value = Deno.env.get(name);
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
}

function normalizeAction(value: unknown) {
  const normalized = String(value || "").trim().toLowerCase();
  if (["release", "block", "fail"].includes(normalized)) {
    return normalized as "release" | "block" | "fail";
  }
  throw new Error("Use action release, block, or fail.");
}

function normalizeText(value: unknown) {
  return String(value || "").trim();
}

function formatPeso(value: unknown) {
  const amount = Number(value || 0);
  return `PHP ${amount.toLocaleString("en-PH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function formatDateTime(value: unknown) {
  if (!value) return "Not available";
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) return "Not available";

  return new Intl.DateTimeFormat("en-PH", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Manila",
  }).format(date);
}

function buildDisplayName(profile: Record<string, unknown> | null, fallback: string) {
  if (!profile) return fallback;

  const displayName = normalizeText(profile.display_name);
  if (displayName) return displayName;

  const fullName = [profile.first_name, profile.last_name]
    .map(normalizeText)
    .filter(Boolean)
    .join(" ")
    .trim();

  return fullName || fallback;
}

async function resolveAuthorizedAdminId(
  request: Request,
  supabaseUrl: string,
  serviceRoleKey: string,
  opsSecret: string
) {
  const serviceSupabase = createClient(supabaseUrl, serviceRoleKey);
  const suppliedSecret = request.headers.get("x-ops-secret");
  const authHeader = request.headers.get("Authorization");
  const accessToken = extractBearerToken(authHeader);

  if (suppliedSecret && suppliedSecret === opsSecret) {
    return {
      authorized: true,
      adminId: null as string | null,
      serviceSupabase,
    };
  }

  if (!accessToken) {
    return {
      authorized: false,
      adminId: null as string | null,
      serviceSupabase,
    };
  }

  const { data: userResult, error: userError } =
    await serviceSupabase.auth.getUser(accessToken);

  if (userError) throw userError;
  const userId = userResult.user?.id || null;
  if (!userId) {
    return {
      authorized: false,
      adminId: null as string | null,
      serviceSupabase,
    };
  }

  const { data: profile, error: profileError } = await serviceSupabase
    .from("profiles")
    .select("id, role")
    .eq("id", userId)
    .maybeSingle();

  if (profileError) throw profileError;

  if (normalizeText(profile?.role).toLowerCase() !== "admin") {
    return {
      authorized: false,
      adminId: null as string | null,
      serviceSupabase,
    };
  }

  return {
    authorized: true,
    adminId: userId,
    serviceSupabase,
  };
}

async function buildReceiptPdf(title: string, subtitle: string, lines: string[]) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdf.embedFont(StandardFonts.Helvetica);
  const accent = rgb(0.68, 0.5, 0.12);
  const ink = rgb(0.12, 0.08, 0.2);
  const soft = rgb(0.38, 0.33, 0.46);

  page.drawText(title, {
    x: 48,
    y: 728,
    size: 24,
    font: boldFont,
    color: ink,
  });

  page.drawLine({
    start: { x: 48, y: 716 },
    end: { x: 312, y: 716 },
    thickness: 2,
    color: accent,
  });

  page.drawText(subtitle, {
    x: 48,
    y: 690,
    size: 11,
    font: regularFont,
    color: soft,
  });

  let cursorY = 648;
  lines.forEach((line) => {
    page.drawText(line, {
      x: 48,
      y: cursorY,
      size: 12,
      font: regularFont,
      color: ink,
      maxWidth: 516,
      lineHeight: 18,
    });
    cursorY -= 28;
  });

  page.drawText("Generated by Carvver", {
    x: 48,
    y: 44,
    size: 10,
    font: regularFont,
    color: soft,
  });

  return await pdf.save();
}

async function uploadReceipt(
  supabase: ReturnType<typeof createClient>,
  {
    orderId,
    userId,
    receiptType,
    bytes,
  }: {
    orderId: string;
    userId: string;
    receiptType: "customer" | "freelancer";
    bytes: Uint8Array;
  }
) {
  const path = `${userId}/${orderId}/${Date.now()}-${receiptType}-receipt.pdf`;
  const { error } = await supabase.storage.from(RECEIPT_BUCKET).upload(path, bytes, {
    contentType: "application/pdf",
    cacheControl: "3600",
    upsert: true,
  });

  if (error) throw error;
  return path;
}

async function insertNotification(
  supabase: ReturnType<typeof createClient>,
  payload: {
    userId: string;
    notificationGroup: "activity" | "system";
    label: string;
    title: string;
    body: string;
    path: string;
    ctaLabel?: string;
    accent?: string;
    accentSoft?: string;
    metadata?: Record<string, unknown>;
  }
) {
  const { error } = await supabase.from("user_notifications").insert({
    user_id: payload.userId,
    notification_group: payload.notificationGroup,
    label: payload.label,
    title: payload.title,
    body: payload.body,
    path: payload.path,
    cta_label: payload.ctaLabel || "Open order",
    accent: payload.accent || null,
    accent_soft: payload.accentSoft || null,
    metadata: payload.metadata || {},
  });

  if (error) throw error;
}

Deno.serve(async (request: Request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed." }, 405);
  }

  try {
    const supabaseUrl = getEnv("SUPABASE_URL");
    const serviceRoleKey = getEnv("SUPABASE_SERVICE_ROLE_KEY");
    const opsSecret = getEnv("OPS_RELEASE_SECRET");
    const { authorized, adminId, serviceSupabase } =
      await resolveAuthorizedAdminId(
        request,
        supabaseUrl,
        serviceRoleKey,
        opsSecret
      );

    if (!authorized) {
      return jsonResponse({ error: "Unauthorized." }, 401);
    }

    const body = await request.json().catch(() => ({}));
    const payoutRequestId = normalizeText(body?.payoutRequestId);
    const action = normalizeAction(body?.action);
    const providerReference = normalizeText(body?.providerReference);
    const note = normalizeText(body?.note);

    if (!payoutRequestId) {
      return jsonResponse({ error: "A payout request id is required." }, 400);
    }

    if (action === "release" && !providerReference) {
      return jsonResponse(
        { error: "A provider reference is required when marking a payout as released." },
        400
      );
    }

    const {
      data: payoutRequest,
      error: payoutError,
    } = await serviceSupabase
      .from("payout_release_requests")
      .select(
        `
        id,
        order_id,
        customer_id,
        freelancer_id,
        amount,
        currency,
        status,
        destination_method,
        destination_account_name,
        destination_account_reference,
        requested_at,
        orders (
          id,
          status,
          service_id,
          total_price,
          freelancer_net,
          payment_reference,
          fulfillment_type,
          created_at,
          completed_at,
          services (
            id,
            title,
            category
          ),
          customer:profiles!orders_customer_id_fkey (
            id,
            first_name,
            last_name,
            display_name
          ),
          freelancer:profiles!orders_freelancer_id_fkey (
            id,
            first_name,
            last_name,
            display_name
          )
        )
      `
      )
      .eq("id", payoutRequestId)
      .maybeSingle();

    if (payoutError) throw payoutError;
    if (!payoutRequest) {
      return jsonResponse({ error: "Payout request not found." }, 404);
    }

    const order = Array.isArray(payoutRequest.orders)
      ? payoutRequest.orders[0]
      : payoutRequest.orders;

    if (!order?.id) {
      return jsonResponse({ error: "The linked order could not be found." }, 404);
    }

    const now = new Date().toISOString();
    let freelancerReceiptPath: string | null = null;
    let customerReceiptPath: string | null = null;

    if (action === "release") {
      const serviceTitle = normalizeText(order.services?.title) || "Carvver order";
      const customerName = buildDisplayName(order.customer, "Customer");
      const freelancerName = buildDisplayName(order.freelancer, "Freelancer");

      const freelancerReceiptBytes = await buildReceiptPdf(
        "Carvver Payout Receipt",
        "This confirms that a queued payout was released after admin review.",
        [
          `Order ID: ${order.id}`,
          `Service: ${serviceTitle}`,
          `Freelancer: ${freelancerName}`,
          `Customer: ${customerName}`,
          `Net payout released: ${formatPeso(payoutRequest.amount)}`,
          `Destination: ${normalizeText(payoutRequest.destination_method) || "Not specified"} / ${
            normalizeText(payoutRequest.destination_account_reference) || "No reference"
          }`,
          `Provider reference: ${providerReference}`,
          `Requested at: ${formatDateTime(payoutRequest.requested_at)}`,
          `Released at: ${formatDateTime(now)}`,
        ]
      );

      const customerReceiptBytes = await buildReceiptPdf(
        "Carvver Completion Receipt",
        "This confirms that the held payment moved through payout release after completion.",
        [
          `Order ID: ${order.id}`,
          `Service: ${serviceTitle}`,
          `Customer: ${customerName}`,
          `Freelancer: ${freelancerName}`,
          `Customer total: ${formatPeso(order.total_price)}`,
          `Freelancer payout released: ${formatPeso(payoutRequest.amount)}`,
          `Original payment reference: ${normalizeText(order.payment_reference) || "Not available"}`,
          `Provider reference: ${providerReference}`,
          `Completed at: ${formatDateTime(order.completed_at)}`,
          `Released at: ${formatDateTime(now)}`,
        ]
      );

      freelancerReceiptPath = await uploadReceipt(serviceSupabase, {
        orderId: order.id,
        userId: payoutRequest.freelancer_id,
        receiptType: "freelancer",
        bytes: freelancerReceiptBytes,
      });

      customerReceiptPath = await uploadReceipt(serviceSupabase, {
        orderId: order.id,
        userId: payoutRequest.customer_id,
        receiptType: "customer",
        bytes: customerReceiptBytes,
      });
    }

    const nextRequestPatch =
      action === "release"
        ? {
            status: "released",
            provider_reference: providerReference,
            ops_note: note || "Released manually by admin.",
            processed_by_admin_id: adminId,
            processed_at: now,
            released_at: now,
            updated_at: now,
            freelancer_receipt_path: freelancerReceiptPath,
            customer_receipt_path: customerReceiptPath,
          }
        : action === "block"
          ? {
              status: "blocked",
              provider_reference: providerReference || null,
              ops_note: note || "Blocked by admin for follow-up.",
              processed_by_admin_id: adminId,
              processed_at: now,
              released_at: null,
              updated_at: now,
            }
          : {
              status: "failed",
              provider_reference: providerReference || null,
              ops_note: note || "Marked failed by admin.",
              processed_by_admin_id: adminId,
              processed_at: now,
              released_at: null,
              updated_at: now,
            };

    const nextOrderPatch =
      action === "release"
        ? {
            escrow_status: "released",
            released_at: now,
          }
        : action === "block"
          ? {
              escrow_status: "blocked",
              released_at: null,
            }
          : {
              escrow_status: "failed",
              released_at: null,
            };

    const { data: updatedRequest, error: updateRequestError } = await serviceSupabase
      .from("payout_release_requests")
      .update(nextRequestPatch)
      .eq("id", payoutRequestId)
      .select(
        `
        id,
        order_id,
        status,
        provider_reference,
        ops_note,
        requested_at,
        processed_at,
        released_at,
        freelancer_receipt_path,
        customer_receipt_path
      `
      )
      .single();

    if (updateRequestError) throw updateRequestError;

    const { error: updateOrderError } = await serviceSupabase
      .from("orders")
      .update(nextOrderPatch)
      .eq("id", payoutRequest.order_id);

    if (updateOrderError) throw updateOrderError;

    const serviceTitle = normalizeText(order.services?.title) || "your order";

    const notificationTasks =
      action === "release"
        ? [
            insertNotification(serviceSupabase, {
              userId: payoutRequest.freelancer_id,
              notificationGroup: "activity",
              label: "Payout released",
              title: `Your payout for "${serviceTitle}" was released.`,
              body: `The queued payout of ${formatPeso(
                payoutRequest.amount
              )} has been processed. Your receipt is now available in the order view.`,
              path: `/dashboard/freelancer/orders/${payoutRequest.order_id}`,
              accent: "rgba(34,197,94,0.94)",
              accentSoft: "rgba(34,197,94,0.14)",
            }),
            insertNotification(serviceSupabase, {
              userId: payoutRequest.customer_id,
              notificationGroup: "system",
              label: "Order completed",
              title: `Payout release finished for "${serviceTitle}".`,
              body: "The held payment has now been processed after your completion confirmation. Your receipt is available in the order view.",
              path: `/dashboard/customer/orders/${payoutRequest.order_id}`,
              accent: "rgba(242,193,78,0.96)",
              accentSoft: "rgba(242,193,78,0.18)",
            }),
          ]
        : [
            insertNotification(serviceSupabase, {
              userId: payoutRequest.freelancer_id,
              notificationGroup: "system",
              label: action === "block" ? "Payout blocked" : "Payout failed",
              title:
                action === "block"
                  ? `Payout follow-up is needed for "${serviceTitle}".`
                  : `Payout processing failed for "${serviceTitle}".`,
              body:
                note ||
                (action === "block"
                  ? "An admin flagged the payout for follow-up."
                  : "An admin marked this payout as failed."),
              path: `/dashboard/freelancer/orders/${payoutRequest.order_id}`,
              accent: "rgba(190,24,93,0.92)",
              accentSoft: "rgba(190,24,93,0.12)",
            }),
          ];

    const notificationResults = await Promise.allSettled(notificationTasks);
    notificationResults.forEach((result) => {
      if (result.status === "rejected") {
        console.error(
          JSON.stringify({
            scope: "release-freelancer-payout",
            stage: "notification.error",
            error: serializeError(result.reason, "Notification insert failed."),
          })
        );
      }
    });

    return jsonResponse({
      success: true,
      payoutRequest: updatedRequest,
      order: {
        id: payoutRequest.order_id,
        ...nextOrderPatch,
      },
    });
  } catch (error) {
    const serialized = serializeError(
      error,
      "Couldn't process the payout release action."
    );
    console.error(
      JSON.stringify({
        scope: "release-freelancer-payout",
        stage: "request.error",
        error: serialized,
      })
    );

    return jsonResponse(
      {
        error: serialized.message,
        debug: serialized.kind === "object" ? serialized.details : undefined,
      },
      500
    );
  }
});
